@extends('layouts.app')

@section('title', 'My Courses - SignGyaan')
@section('description', 'View your SignGyaan courses, saved lesson progress and completed learning.')

@section('content')
<section class="border-b border-sign-border bg-sign-soft py-8 sm:py-12"><x-container><nav class="flex flex-wrap gap-2 text-sm text-sign-muted" aria-label="Breadcrumb"><a href="{{ route('dashboard') }}" class="hover:text-sign-primary">Dashboard</a><span aria-hidden="true">/</span><span class="font-semibold text-sign-primary">My Courses</span></nav><div class="mt-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-sm font-semibold uppercase tracking-wider text-sign-cyan-dark">Your courses</p><h1 class="mt-2 font-heading text-3xl font-semibold text-sign-primary sm:text-5xl">My Courses</h1><p class="mt-4 max-w-2xl text-sm leading-7 text-sign-muted">Continue active courses, review completed courses and see detailed progress for every published lesson.</p></div><a href="{{ route('explore') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-sign-primary px-5 py-3 text-sm font-semibold text-white">Explore Courses</a></div></x-container></section>
<section class="bg-white py-8 sm:py-12 lg:py-16"><x-container>
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Course summary">@foreach ([['Tracked courses',$courseSummary['total']],['In progress',$courseSummary['in_progress']],['Completed',$courseSummary['completed']],['Overall progress',$courseSummary['overall_progress'].'%']] as $summary)<div class="rounded-2xl border border-sign-border p-5 sm:rounded-3xl sm:p-6"><p class="text-sm font-semibold text-sign-muted">{{ $summary[0] }}</p><p class="mt-3 font-heading text-3xl font-semibold text-sign-primary">{{ $summary[1] }}</p></div>@endforeach</div>
@if ($courses->isNotEmpty())
<section class="mt-10" aria-labelledby="my-courses-heading"><p class="text-sm font-semibold uppercase tracking-wider text-sign-cyan-dark">Course library</p><h2 id="my-courses-heading" class="mt-2 font-heading text-2xl font-semibold text-sign-primary sm:text-3xl">Your saved courses</h2><div class="mt-5 grid gap-5 lg:grid-cols-2">
@foreach ($courses as $course)
<article class="flex flex-col rounded-2xl border border-sign-border p-5 sm:rounded-3xl sm:p-6"><div class="flex flex-wrap justify-between gap-3"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-sign-soft px-3 py-1 text-xs font-semibold text-sign-primary">{{ $course['subject'] }}</span><span class="rounded-full bg-sign-light px-3 py-1 text-xs font-semibold text-sign-cyan-dark">{{ $course['course_level'] }}</span></div><span class="text-xs font-semibold text-sign-muted">{{ $course['status'] === 'completed' ? 'Completed' : 'In progress' }}</span></div><h3 class="mt-4 font-heading text-xl font-semibold text-sign-primary sm:text-2xl">{{ $course['course_title'] }}</h3><p class="mt-2 text-sm text-sign-muted">{{ $course['completed_lessons'] }} of {{ $course['total_lessons'] }} lessons completed</p><div class="mt-4 h-2 overflow-hidden rounded-full bg-sign-soft" role="progressbar" aria-label="{{ $course['course_title'] }} progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $course['progress_percent'] }}"><div class="h-full rounded-full bg-sign-primary" style="width: {{ $course['progress_percent'] }}%"></div></div><p class="mt-2 text-xs font-semibold text-sign-cyan-dark">{{ $course['progress_percent'] }}% complete</p>
@if ($course['status'] === 'in-progress')<div class="mt-5 rounded-2xl bg-sign-soft p-4"><p class="text-xs font-semibold uppercase tracking-wide text-sign-muted">Continue from</p><p class="mt-1 text-sm font-semibold text-sign-primary">{{ $course['current_lesson_title'] ?: 'Current lesson' }}</p>@if ($course['current_unit_title'])<p class="mt-1 text-xs text-sign-muted">{{ $course['current_unit_title'] }}</p>@endif</div>@endif
<div class="mt-auto flex flex-col gap-2 pt-5 sm:flex-row">@if ($course['status'] === 'in-progress')<a href="{{ $course['resume_url'] }}" class="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl bg-sign-primary px-4 py-3 text-sm font-semibold text-white">Continue Course</a>@endif<a href="{{ route('my-courses.progress', ['subject' => $course['subject_slug'], 'course' => $course['course_slug']]) }}" class="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl border border-sign-primary px-4 py-3 text-sm font-semibold text-sign-primary hover:bg-sign-soft">View Progress</a></div></article>
@endforeach
</div></section>
@else
<section class="mt-10 rounded-2xl border border-dashed border-sign-border bg-sign-soft p-8 text-center sm:rounded-3xl"><h2 class="font-heading text-2xl font-semibold text-sign-primary">No saved courses yet</h2><p class="mt-2 text-sm text-sign-muted">Start a published lesson and save your place to begin tracking progress.</p><a href="{{ route('subjects') }}" class="mt-5 inline-flex min-h-11 items-center rounded-xl bg-sign-primary px-5 py-3 text-sm font-semibold text-white">Browse Subjects</a></section>
@endif
</x-container></section>
@endsection
